Fruit =[]
f1 = input("Enter Fruit name:")
Fruit.append(f1)
f2 = input("Enter Fruit name:")
Fruit.append(f2)
f3 = input("Enter Fruit name:")
Fruit.append(f3)
f4= input("Enter Fruit name:")
Fruit.append(f4)
f5 = input("Enter Fruit name:")
Fruit.append(f5)
f6 = input("Enter Fruit name:")
Fruit.append(f6)
f7 = input("Enter Fruit name:")
Fruit.append(f7)
print(Fruit)
